all:
	javac -d classes/ -cp classes/ IllegalIDException.java
	javac -d classes/ -cp classes/ NotEmptyException.java
	javac -d classes/ -cp classes/ Node.java
	javac -d classes/ -cp classes/ MySearchTree.java
	javac -d classes/ -cp classes/ EmployeeQueue.java
	javac -d classes/ -cp classes/ OrgHierarchyInterface.java
	javac -d classes/ -cp classes/ OrgHierarchy.java
	javac -d classes/ -cp classes/ Tester.java
	javac -d classes/ -cp classes/ Tester2.java
	javac -d classes/ -cp classes/ Tester3.java
	java -cp classes/ Tester
	java -cp classes/ Tester2
	java -cp classes/ Tester3

clean:
	rm classes/IllegalIDException.class 
	rm classes/NotEmptyException.class
	rm classes/OrgHierarchyInterface.class
	rm classes/OrgHierarchy.class
	rm classes/Tester.class
	rm classes/EmployeeQueue.class
	rm classes/Node.class
	rm classes/MySearchTree.class
 
