all:
	javac -d classes/ -cp classes/ GrowableArray.java
	javac -d classes/ -cp classes/ HashMap.java
	javac -d classes/ -cp classes/ Anagram.java
	java -cp classes/ Anagram vocabulary.txt input.txt

clean:
	rm classes/Anagram.class 
	rm classes/HashMap.class
	rm classes/GrowableArray.class
 